### ISSUE TITLE
No watched items in my watchlist!

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#10]
## Value statement

As a user, I don't want to see watched items in my watchlist so that I have an overview of all items I still want to experience.

## Acceptance criteria

- [ ] When I check the checkbox of an item in my watchlist, it should disappear from my watchlist
- [ ] It should then reappear in my collection

## Complexity

S

## Tasks

- [ ] home page shows only isWatched === false
