### ISSUE TITLE
Add notes to items in my collection

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#11]
## Value statement

As a user, I want to add notes to items in my collection so that I can remember what I thought about my cultural experience and share my thoughts with others when needed.

## Acceptance criteria

- [ ] I can add a note to collection items

## Complexity

XL

## Tasks

- [ ] If I haven't created a second array yet, I guess I need one now: When checking the checkbox in Watchlist, the corresponding item is pushed into a new array: collectionItems
- [ ] the item is deleted from the first array watchlistItems
- [ ] when editing an item in Collection, the user can leave a note
