### ISSUE TITLE
Basic orientation in the app

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#2]
## Value statement

As a user, I want to to get access to the app so that I can get an idea of how I can orientate myself and what options the app offers to me.

## Acceptance criteria

- [ ] I can enter the app
- [ ] I can use the navigation bar to change to another view
- [ ] I can see the app title on top
- [ ] each site tells me what I will be able to find there later on
- [ ] the navigation bar helps me to understand which view I see

## Complexity

S

## Tasks

- [ ] create wireframes
- [ ] create user stories

**Comment by felixcanditt** [comment]
maybe split up into several user stories (base, nav bar)
