### ISSUE TITLE
show different watchlist cards depending on category

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#21]
## Value statement

As a user, I want to see all details I selected on screen.

## Acceptance criteria

- [x] When I add an item to Watchlist, I want to see all details I submitted on screen

## Complexity

L

## Tasks

- [x] Add if/else statements to rendering of watchlist cards, according to chosen categories
- [x] Add text to cards depending on category (e.g. location and time)
- [x] Change checkbox text according to category (e.g. watched film vs read book)
