### ISSUE TITLE
plus icon for new entries to wishlist and collection

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#26]
## Value statement

The form right on the top of the looks horrible. I want to see a "plus" icon so that I can open the form by clicking on the icon if I want to add an item. If I want to edit an item, the form should open once I click "edit" in an item.

## Description

<img width="682" alt="Bildschirmfoto 2021-06-21 um 11 34 26" src="https://user-images.githubusercontent.com/82392063/122741555-5c8a8f80-d285-11eb-8851-e53e56fb9421.png">

## Acceptance criteria

- [ ] I see a plus icon on top of the page in Watchlist and Library
- [ ] When I click on it, a form opens that helps me to add an item
- [ ] When I click edit in one item, the form opens too
- [ ] When I submit the form or cancel, the form disappears again

## Complexity

L

## Tasks

- [ ] replace the fixed form on screen by a modal
- [ ] modal appears when clicking on the plus icon or on edit in an item card
- [ ] modal disappears when submitting/ canceling the form
- [ ] style the plus icon
