### ISSUE TITLE
Add a basic entry

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#3]
## Value statement

As a user, I want to to add and submit a basic entry so that my watchlist doesn't look that empty.

## Description

<img width="254" alt="Bildschirmfoto 2021-06-04 um 18 47 00" src="https://user-images.githubusercontent.com/82392063/120836073-7332a600-c565-11eb-8937-ad394641fdd9.png">

## Acceptance criteria

- [ ] I see a form in the watchlist section
- [ ] I can fill the form and submit it

## Complexity

M

## Tasks

- [ ] add a form
- [ ] form content: title, 2 input fields (name, category), 1 button
- [ ] when submitting the form, a new object is created and pushed to an array/ useState

**Comment by felixcanditt** [comment]
maybe split up into several user stories (form and submitting, display cards)
