### ISSUE TITLE
Edit watchlist items

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#7]
## Value statement

As a user, I want to edit watchlist items so that I can change my list whenever I want.

## Acceptance criteria

- [ ] I can tell the app that I want to change an item
- [ ] I can change the item and submit it
- [ ] I see the edited result immediately on screen

## Complexity

M

## Tasks

- [ ] add options to the server: PUT
- [ ] add a button to all items: edit
- [ ] watchlist form should show content to be edited
