### ISSUE TITLE
I watched a film and want to see that in my watchlist

### ISSUE THREAD

**Issue by felixcanditt** [felixcanditt/kultur-notiert#8]
## Value statement

As a user, I want to edit and delete watchlist items so that I can change my list whenever I want.

## Acceptance criteria

- [ ] I can delete a wishlist item
- [ ] I can tell the app that I want to change an item
- [ ] I can change the item and submit it
- [ ] I see the edited result immediately on screen

## Complexity

L

## Tasks

- [ ] add options to the server: PUT
- [ ] add options to the server: DELETE
- [ ] add a button to all items: edit
- [ ] add a button to all items: delete
